services:
  botmanager:
    image: hub.demolite.de/demoreg/botmanager
    container_name: botmanager
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: BotManager.Main/Dockerfile
      args:
        - CERT_PASS=${cert_pass}
    ports:
      - "8087:80"
      - "8088:443"
    volumes:
      - "./dbdata/:/app/dbdata/"
      - "./image/:/app/image/"